### ISSUE TITLE
Missing CSS for adapt-contents

### ISSUE THREAD

**Issue by nfon-christophe** [saga-nfon/adapt-nfon-theme#7]
Hi Team,

I have just added the "Content" extension plugin on one of the test course (sorry we hadn't tested that before), but I get build errors as the CSS for that plugin is missing.

Can you please have a look and try to fix it?

In term of colors, etc., it should probably look like the "page level progress" extension (not sure until I see it working).

**Comment by hardik-sagacity** [comment]
I have checked the content plugin and installed it. I have enabled all the missing CSS varibales for the extension. 
But by only changing the CSS wont make this extension work.
there are many javascript errors from the extension because this plugin is using legacy functions from old adapt framework(v2 ) and not compatible with newer version. It will be difficult to change these functions because the extension is designed and built around the previous adapt framework.

**Comment by nfon-christophe** [comment]
We will not use adapt-content
